### PR TITLE
Add cors

### PR DESCRIPTION
**Pull request by AnthonyRonning**
This gives browser based wallets the ability to connect to c-lightning via spark server.

### CODE REVIEW

**Comment by AnthonyRonning** [comment]
Doesn't look like the build failure is due to this PR, but let me know if there is anything I should do.

**Comment by shesek** [comment]
What are you trying to accomplish?

Setting this up like this would give any website you open in your browser the ability to access your c-lightning wallet... which is probably not what you want. This should at least be behind an optional configuration option, off by default, and with the ability to configure a specific origin rather than setting it to "*".

**Comment by AnthonyRonning** [comment]
I'm creating a non-custodial web based wallet: https://github.com/AnthonyRonning/ShineWallet

A couple things on CORS:
1. It's only a suggestion, you can configure browsers to turn off the check and access anyways. 
2. It does not give any website the ability to access spark, since passing authentication token is still necessary on every api call.
3. CORS is mostly meant for restricting access to resources (pics, videos, files, etc.) from one site to another through the webpage. 
4. Making it optional will lead to even more difficulty, especially where users don't directly access set up their spark (ie btcpay). 

I don't see any harm in keeping it on by default, especially since auth is necessary anyways.

**Comment by shesek** [comment]
> It does not give any website the ability to access spark, since passing authentication token is still necessary on every api call.

Users are also authenticated using a cookie. If an attacker is able to send requests with the user's cookie and read the response, he could extract the API access token from the HTML of the webpage. The `SameSite` directive could help here (and is being set), but its [not supported by all browsers](https://caniuse.com/same-site-cookie-attribute).

Exposing the spark web server to allow CORS requests from all origins is definitely not safe. This cannot be the default and has to allow specifying an explicit list of allowed origins.

**Comment by AnthonyRonning** [comment]
Cookie auth is only supported if `Access-Control-Allow-Credentials` is set to `true`. 

Per the [cors github](https://github.com/expressjs/cors):
> credentials: Configures the Access-Control-Allow-Credentials CORS header. Set to true to pass the header, otherwise it is omitted.

I can test out cookie auth later tonight to verify that they do not work.

**Comment by shesek** [comment]
Ok, that's better, I thought `cors`'s defaults were more permissive.

But even so, I still wouldn't open CORS to all origins by default. It would still allow probing the web server from the user's browser, which would make it possible for an attacker to detect that the user has spark installed and that he's a bitcoin/lightning user. (see [lan-js](https://github.com/joevennix/lan-js))

**Comment by AnthonyRonning** [comment]
Sounds good, I agree now. Was also talking to others in a PR in LND and it could also be the case that an attacker targets an individual where they already know their credentials but can't get passed the firewall or the proxy is on accessible on a local IP. 

I'll try to get to it this weekend, thanks for the dialog.

**Comment by shesek** [comment]
I implemented this as an opt-in with the ability to set an explicit list of allowed origins in https://github.com/shesek/spark-wallet/commit/05c7ee0a00eaf41267e3197dd018affa36b55eec.

**Comment by shesek** [comment]
I implemented this as an opt-in with the ability to set an explicit list of allowed origins in https://github.com/shesek/spark-wallet/commit/c190ae904197b4f21d9f8f5321bbced340180f69.

**Pull request closed without merging**
